events {}

http {
  upstream backend_pool {
    # Round robin por defecto
    server web1:80;
    server web2:80;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://backend_pool;

      # Evidencia: muestra qué backend respondió (en headers)
      add_header X-Backend $upstream_addr always;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
